name: "Sync reviewers and assignees"
on:
  pull_request:
    types: [review_requested,review_request_removed,assigned,unassigned]

jobs:
  sync_reviewers_assignees:
    runs-on: ubuntu-latest
    steps:
      - uses: rubeus90/auto-sync-reviewer-assignee@v1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
