name: Add label if needs a review.
on:
  pull_request:
    types: [opened, edited, review_requested, review_request_removed]

jobs:
  check_milestone:
    runs-on: ubuntu-latest
    steps:
      - name: Check milestone
        uses: guillaumevalverde/ActionLabelReviewerNeeded@v1.0.21
        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
