name: Add label if needs a review.
on:
  pull_request:
    types: [opened, edited, review_requested]
  push:
    branches:
      - testing_label_action

jobs:
  check_milestone:
    runs-on: ubuntu-latest
    steps:
      - name: Check milestone
        uses: guillaumevalverde/ActionLabelReviewerNeeded@v1.0.2
        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
