name: Assign reviewers based on assignees
on:
  pull_request:
    types: [review_requested]

jobs:
  assignee_to_reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Assignee to Reviewer
        uses: guillaumevalverde/assignee-to-reviewer-action@v1.0.24
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
