name: Check milestone is set up.
on:
  pull_request:
    types: [opened]
  issues:
    types: [milestoned, demilestoned]
    

jobs:
  check_milestone:
    runs-on: ubuntu-latest
    steps:
      - name: Check milestone
        uses: guillaumevalverde/check_milestone_action@v1.0.11
        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
