name: Assign reviewers based on assignees
on:
  pull_request:
    types: [review_requested, review_request_removed]

jobs:
  assignee_to_reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Check milestone
        uses: guillaumevalverde/check_milestone_action@v1.0.0
        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
